services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: nuts-server
    env: docker # valid values: https://render.com/docs/yaml-spec#environment
    plan: free # optional; defaults to starter
    numInstances: 1
    envVars:
      - key: GITHUB_REPO
        sync: false # will not be copied to preview environments
      - key: GITHUB_TOKEN
        sync: false 
      - key: PORT
        value: 5000 
      - key: TRUST_PROXY
        value: loopback